### ISSUE TITLE
consul + multi-host + multi-datacenter

### ISSUE THREAD

**Issue by tiagoalves83** [DonMills/dockeroverlayvyos#1]
Can you give some hints about a deploy that I am doing ?
The image below shows the actual topology. (2 cloud providers talking to each other.)

![docker-network](https://cloud.githubusercontent.com/assets/2650689/16710650/a9bfbb1e-460c-11e6-9a5a-92222570b074.png)
- How to deploy a docker overlay network between datacenters (private networks A/B) ?
  consul.io can handle multi-datacenter K/V datastore where latency can be a problem.
- How to add a private legacy service (running outside container) to docker overlay network ?
  eg: A docker container running inside an overlay network 10.1.100.0/24 talking to a service (not containerized) in the same network.

**Comment by DonMills** [comment]
Sorry it took me a while to respond.
- for your first question, the standard docker overlay should have no problem operating over the internet as long as you have all necessary ports opened in perimeter firewalls.  The issue might be that the data will be unencrypted between the two, unless you added an additional layer of an ipsec network between the two datacenters.  This would however have the side effect of lowering the MTU size of the possible packets that could be transmitted (which are already lower than normal due to the vxlan encapsulation), so you would have to account for that in your planning.
  A second option would be to use an alternative plugin other than the default.  The Weave plugin offers encryption built into it (https://www.weave.works/docs/net/latest/how-it-works/encryption/).  
  Third option is to use some higher level tool such as Rancher that has built in ipsec networking capabilities.
- As far as  your second question, you could do this multiple ways, especially dependent on what choice you made for the first question.  Using the default plugin, I would probably explore using a proxy or NAT container that sat on the container network and proxied/translated traffic to the outside service via either a docker bridge interface or some of the newer experimental macvlan/ipvlan drivers.  

Hope this is still helpful!
